### ISSUE TITLE
Precisiones (tooltips) a leyendas y campos

### ISSUE THREAD

**Issue by FernandoArribas** [joseluis-garcia/Solidar#11]
Conforme más usuarios van utilizando Solidar, se va haciendo apremiante añadir comentarios (tooltips) a la interfaz de Solidar

**Comment by FernandoArribas** [comment]
Adjunto las primeras precisiones a leyendas y campos. Hacedme observaciones para seguir del mismo modo o cambiar.

[Solidar - precisiones 0.1.ods](https://github.com/joseluis-garcia/Solidar/files/10098369/Solidar.-.precisiones.0.1.ods)

**Comment by joseluis-garcia** [comment]
Implementadas en version 20221128 solo en castellano.
