### ISSUE TITLE
No automatizar la cuantía de la subvención de los Fondos Next Generation

### ISSUE THREAD

**Issue by FernandoArribas** [joseluis-garcia/Solidar#14]
Actualmente se calcula en función de la potencia de todos los paneles instalados la cuantía de la subvención de los fondos europeos. El usuario únicamente tiene que decir si forma parte de una instalación colectiva o individual.

Ahora bien para el caso de aquellos usuarios que estén haciendo sus cálculos en Solidar según su consumo individual pero que pertenezcan a una comunidad de propietarios donde se instalen muchos más paneles que los suyos, habrá que informar al simulador de cuánta potencia final se va a instalar para que se calcule correctamente el importe de la subvención.

Sugiero algo parecido (o mejor) a lo siguiente:

![image](https://user-images.githubusercontent.com/118930659/204135817-d0a1134d-2591-4eea-a4f7-1ca0a3dbc3a8.png)

**Comment by joseluis-garcia** [comment]
Esos son los valores que se usan.

**Comment by FernandoArribas** [comment]
¿Cómo sabe el simulador si tiene que aplicar 710€ o 535€ si no sabe el número total de paneles que se instalarán en una comunidad?

**Comment by joseluis-garcia** [comment]
El simulador se basa en la potencia instalada según el número de paneles que decida el usuario y su potencia unitaria. El usuario solo indica si tiene subvención individual o comunitaria.

Supongo que en caso de que la potencia instalada real sea superior a la que se esta indicando en la simulación tampoco sería correcto asignarle el total de la subvención a la unidad que esta simulando ya que le llegaría solo un porcentaje de la misma por lo que entramos en el caso del simulador para comunidades que debemos empezar a programar

**Comment by FernandoArribas** [comment]
Conforme
