### ISSUE TITLE
Balance financiero: incluir al menos tantos años en la tabla como los de bonificaciones por IBI

### ISSUE THREAD

**Issue by FernandoArribas** [joseluis-garcia/Solidar#15]
Un vecino de una comunidad de propietarios en Madrid me ha sugerido incluir en las tabla de retorno tantos años como los de bonificación del IBI mas uno (en caso de Madrid, la tabla comprendería cuatro años como mínimo). Así, dice él, los vecinos se darían cuenta de cuánto se gana....
Sugiero que, al menos, se tenga en cuenta en la tabla todos los años de la bonificación. En mi caso, que tengo tarifas Generation kWh (muy ventajosas), la tabla referida constaría de menos años que los tres en que se bonifica el IBI. Merece la pena que aperezcan los tres años:

![image](https://user-images.githubusercontent.com/118930659/204137029-afdbace1-faca-4403-bf51-e6918659a736.png)

**Comment by joseluis-garcia** [comment]
Hecho en version 20221128-1
